### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by KshZh** [tomfran/LSM-Tree#2]
![image](https://github.com/tomfran/LSM-Tree/assets/30435672/3d6cb531-d3c6-44d3-97b4-d2f078352083)
![image](https://github.com/tomfran/LSM-Tree/assets/30435672/a3de6a45-ccf0-464e-86a3-8ab9cf6371c1)
![image](https://github.com/tomfran/LSM-Tree/assets/30435672/ba0ffb2e-3a0e-4e37-a176-bf968abd6ab1)

**Comment by tomfran** [comment]
Nice catch, I'll fix it thanks
